"""Meeting transcripts: speaker-attributed dialogue, stored as plain JSON.

Only the transcript is ever persisted — meeting audio spools to a temp WAV
during recording and is deleted the moment processing finishes (or fails, or
is cancelled). Each meeting is one hand-editable JSON file in
settings.meetings_dir(), keyed by an immutable id so renaming never moves a
file:

    {
      "id": "20260708-143212-a3f9",
      "title": "Meeting — Jul 8, 2:32 PM",
      "created": "2026-07-08T14:32:12",
      "duration_seconds": 1832.5,
      "segments": [
        {"speaker": "Speaker 1", "start": 0.4, "end": 12.9, "text": "..."}
      ]
    }

This module is pure logic (stdlib only) so the alignment algorithm and the
store are testable without the model, sherpa-onnx, or AppKit. The alignment
inputs are duck-typed: `sentences` only needs .start/.end/.tokens (tokens
need .start/.end/.duration/.text), matching parakeet_mlx's AlignedSentence
without importing it.
"""

import json
import os
import re
import secrets
from dataclasses import dataclass
from datetime import datetime

from . import config, settings

# Ids double as filenames; generated by Meeting.new, validated on load.
_ID_RE = re.compile(r"[0-9]{8}-[0-9]{6}-[0-9a-f]{4}")

# A diarization turn further than this from a token is considered unrelated;
# the token then inherits its predecessor's speaker instead (mid-sentence
# continuity beats a distant turn).
_MAX_TURN_DISTANCE_SECONDS = 2.0


@dataclass
class MeetingSegment:
    speaker: str
    start: float
    end: float
    text: str
    confidence: float | None = None
    overlap: bool = False
    profile_id: str | None = None
    cluster_id: int | None = None


@dataclass(frozen=True)
class DiarizationTurn:
    start: float
    end: float
    speaker: int
    confidence: float | None = None
    overlap: bool = False
    profile_id: str | None = None


class Meeting:
    def __init__(
        self,
        meeting_id: str,
        title: str,
        created: str,
        duration_seconds: float,
        segments: list[MeetingSegment],
        capture_mode: str = "mic_only",
        system_audio_status: str = "legacy_unknown",
        track_offsets_seconds: dict[str, float] | None = None,
    ) -> None:
        self.meeting_id = meeting_id
        self.title = title
        self.created = created
        self.duration_seconds = duration_seconds
        self.segments = segments
        self.capture_mode = capture_mode
        self.system_audio_status = system_audio_status
        self.track_offsets_seconds = track_offsets_seconds or {"mic": 0.0}

    # -- storage --------------------------------------------------------

    @property
    def path(self):
        return settings.meetings_dir() / f"{self.meeting_id}.json"

    @classmethod
    def new(
        cls,
        segments: list[MeetingSegment],
        duration_seconds: float,
        *,
        capture_mode: str = "mic_only",
        system_audio_status: str = "unavailable",
        track_offsets_seconds: dict[str, float] | None = None,
    ) -> "Meeting":
        now = datetime.now()
        meeting_id = f"{now.strftime('%Y%m%d-%H%M%S')}-{secrets.token_hex(2)}"
        # e.g. "Meeting — Jul 8, 2:32 PM" (%-I is glibc/BSD strftime; fine on macOS)
        title = f"Meeting — {now.strftime('%b %-d, %-I:%M %p')}"
        return cls(
            meeting_id=meeting_id,
            title=title,
            created=now.isoformat(timespec="seconds"),
            duration_seconds=duration_seconds,
            segments=segments,
            capture_mode=capture_mode,
            system_audio_status=system_audio_status,
            track_offsets_seconds=track_offsets_seconds,
        )

    @classmethod
    def load(cls, meeting_id: str) -> "Meeting":
        # Same defense as Profile.load: the id becomes a filesystem path and
        # must not be trusted blindly.
        if not _ID_RE.fullmatch(meeting_id):
            raise ValueError(f"Invalid meeting id: {meeting_id!r}")
        path = settings.meetings_dir() / f"{meeting_id}.json"
        data = json.loads(path.read_text(encoding="utf-8"))
        raw_offsets = data.get("track_offsets_seconds", {"mic": 0.0})
        if not isinstance(raw_offsets, dict):
            raw_offsets = {"mic": 0.0}
        segments = [
            MeetingSegment(
                speaker=str(s["speaker"]),
                start=float(s["start"]),
                end=float(s["end"]),
                text=str(s["text"]),
                confidence=(
                    float(s["confidence"]) if s.get("confidence") is not None else None
                ),
                overlap=bool(s.get("overlap", False)),
                profile_id=s.get("profile_id"),
                cluster_id=(
                    int(s["cluster_id"]) if s.get("cluster_id") is not None else None
                ),
            )
            for s in data.get("segments", [])
        ]
        return cls(
            meeting_id=meeting_id,
            title=data.get("title") or meeting_id,
            created=data.get("created") or "",
            duration_seconds=float(data.get("duration_seconds", 0.0)),
            segments=segments,
            capture_mode=str(data.get("capture_mode", "mic_only")),
            system_audio_status=str(
                data.get("system_audio_status", "legacy_unknown")
            ),
            track_offsets_seconds={
                str(name): float(offset)
                for name, offset in raw_offsets.items()
                if name in {"mic", "system"}
            },
        )

    def save(self) -> None:
        """Write the meeting as JSON, atomically (same rationale as
        Profile.save: never leave a half-written file for the list to skip)."""
        self.path.parent.mkdir(parents=True, exist_ok=True)
        data = (
            json.dumps(
                {
                    "id": self.meeting_id,
                    "title": self.title,
                    "created": self.created,
                    "duration_seconds": self.duration_seconds,
                    "capture_mode": self.capture_mode,
                    "system_audio_status": self.system_audio_status,
                    "track_offsets_seconds": {
                        name: round(offset, 6)
                        for name, offset in self.track_offsets_seconds.items()
                        if name in {"mic", "system"}
                    },
                    "segments": [
                        {
                            "speaker": s.speaker,
                            "start": round(s.start, 2),
                            "end": round(s.end, 2),
                            "text": s.text,
                            **(
                                {"confidence": round(s.confidence, 4)}
                                if s.confidence is not None
                                else {}
                            ),
                            **({"overlap": True} if s.overlap else {}),
                            **({"profile_id": s.profile_id} if s.profile_id else {}),
                            **(
                                {"cluster_id": s.cluster_id}
                                if s.cluster_id is not None
                                else {}
                            ),
                        }
                        for s in self.segments
                    ],
                },
                indent=2,
                ensure_ascii=False,
            )
            + "\n"
        )
        tmp_path = self.path.with_suffix(".json.tmp")
        tmp_path.write_text(data, encoding="utf-8")
        os.replace(tmp_path, self.path)

    def rename(self, title: str) -> None:
        title = title.strip()
        if not title:
            raise ValueError("Meeting title can't be empty.")
        self.title = title
        self.save()

    def delete(self) -> None:
        self.path.unlink(missing_ok=True)

    def relabel_speaker(
        self, segment_index: int, label: str, *, all_matching: bool = False
    ) -> None:
        """Relabel one segment, or every segment sharing its current label."""
        label = label.strip()
        if not label:
            raise ValueError("Speaker label can't be empty.")
        if not 0 <= segment_index < len(self.segments):
            raise IndexError("Invalid meeting segment index.")
        old = self.segments[segment_index].speaker
        for index, segment in enumerate(self.segments):
            if index == segment_index or (all_matching and segment.speaker == old):
                segment.speaker = label
                segment.profile_id = None
                segment.confidence = None
        self.save()


def list_meetings() -> list[Meeting]:
    """Every stored meeting, newest first, skipping any that won't parse
    (hand-editable JSON — one bad file must not take the list down)."""
    meetings_dir = settings.meetings_dir()
    meetings = []
    for path in meetings_dir.glob("*.json"):
        if not _ID_RE.fullmatch(path.stem):
            continue
        try:
            meetings.append(Meeting.load(path.stem))
        except (OSError, ValueError, KeyError) as err:
            print(f"  Skipping meeting '{path.stem}' (couldn't read it): {err}")
    meetings.sort(key=lambda m: m.meeting_id, reverse=True)
    return meetings


# -- rendering ------------------------------------------------------------


def _timestamp(seconds: float) -> str:
    seconds = max(0, int(seconds))
    h, rem = divmod(seconds, 3600)
    m, s = divmod(rem, 60)
    return f"{h:02d}:{m:02d}:{s:02d}"


def _duration_text(seconds: float) -> str:
    m = int(seconds) // 60
    if m >= 60:
        return f"{m // 60} h {m % 60} min"
    return f"{m} min" if m else f"{int(seconds)} s"


def render_txt(meeting: Meeting) -> str:
    lines = [
        meeting.title,
        f"{meeting.created}  ·  {_duration_text(meeting.duration_seconds)}",
        "",
    ]
    for seg in meeting.segments:
        lines.append(f"[{_timestamp(seg.start)}] {seg.speaker}: {seg.text}")
    return "\n".join(lines) + "\n"


def render_md(meeting: Meeting) -> str:
    lines = [
        f"# {meeting.title}",
        "",
        f"*{meeting.created}  ·  {_duration_text(meeting.duration_seconds)}*",
        "",
    ]
    for seg in meeting.segments:
        lines.append(f"**{seg.speaker}** [{_timestamp(seg.start)}]: {seg.text}")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


# -- speaker/text alignment -------------------------------------------------


def align_speakers(sentences, turns) -> list[MeetingSegment]:
    """Attribute transcribed sentences to diarization speakers.

    `sentences`: time-ordered objects with .start/.end/.tokens (tokens carry
    .start/.end/.duration/.text) — parakeet_mlx AlignedSentence-shaped.
    `turns`: [(start, end, speaker_int)] from the diarizer, any order.

    Tokens vote for the turn containing their midpoint; a token in no turn
    falls to the nearest turn unless it is further than
    _MAX_TURN_DISTANCE_SECONDS away, in which case it inherits its
    predecessor's speaker (the diarizer missed a beat mid-utterance more
    often than the room actually changed speakers). Each sentence goes to
    its duration-majority speaker — sentence-level voting absorbs the jitter
    tokens pick up at turn boundaries. Consecutive same-speaker sentences
    merge into one segment, and speakers are numbered by first appearance.
    """
    if not sentences:
        return []
    turns = [
        turn
        if isinstance(turn, DiarizationTurn)
        else DiarizationTurn(float(turn[0]), float(turn[1]), int(turn[2]))
        for turn in turns
    ]
    turns.sort(key=lambda t: t.start)

    def token_speaker(token, previous: int | None) -> int | None:
        mid = (token.start + token.end) / 2
        nearest, nearest_distance = None, None
        for turn in turns:
            if turn.start <= mid <= turn.end:
                return turn.speaker
            distance = turn.start - mid if mid < turn.start else mid - turn.end
            if nearest_distance is None or distance < nearest_distance:
                nearest, nearest_distance = turn.speaker, distance
        if nearest is None:
            return previous
        if nearest_distance > _MAX_TURN_DISTANCE_SECONDS and previous is not None:
            return previous
        return nearest

    # Split at sustained in-sentence speaker changes, while absorbing short
    # boundary jitter with the sentence's duration-majority speaker.
    attributed: list[tuple[object, list[object], int]] = []
    previous: int | None = None
    for sentence in sentences:
        weights: dict[int, float] = {}
        token_speakers: list[tuple[object, int]] = []
        for token in sentence.tokens:
            speaker = token_speaker(token, previous)
            if speaker is None:
                continue
            previous = speaker
            token_speakers.append((token, speaker))
            weights[speaker] = weights.get(speaker, 0.0) + max(token.duration, 1e-3)
        if weights:
            winner = max(weights.items(), key=lambda kv: kv[1])[0]
        else:
            # No turns at all (diarization found nothing): single speaker.
            winner = attributed[-1][2] if attributed else 0
        if not token_speakers:
            attributed.append((sentence, [], winner))
            continue
        runs: list[list[tuple[object, int]]] = []
        for item in token_speakers:
            if not runs or runs[-1][-1][1] != item[1]:
                runs.append([item])
            else:
                runs[-1].append(item)
        normalized_runs: list[tuple[list[object], int]] = []
        for run in runs:
            duration = sum(max(token.duration, 1e-3) for token, _ in run)
            speaker = run[0][1]
            if speaker != winner and (
                len(run) < 2 or duration < config.DIARIZATION_SPLIT_MIN_SECONDS
            ):
                speaker = winner
            tokens = [token for token, _ in run]
            if normalized_runs and normalized_runs[-1][1] == speaker:
                normalized_runs[-1][0].extend(tokens)
            else:
                normalized_runs.append((tokens, speaker))
        if len(normalized_runs) == 1:
            attributed.append((sentence, [], normalized_runs[0][1]))
        else:
            attributed.extend(
                (sentence, tokens, speaker) for tokens, speaker in normalized_runs
            )

    # Merge consecutive same-speaker sentences; label by first appearance.
    labels: dict[int, str] = {}
    profile_ids: dict[int, str | None] = {}
    profile_labels = {turn.profile_id for turn in turns if turn.profile_id}
    segments: list[MeetingSegment] = []
    for sentence, tokens, speaker in attributed:
        if speaker not in labels:
            profile = next(
                (t.profile_id for t in turns if t.speaker == speaker and t.profile_id),
                None,
            )
            if profile:
                labels[speaker] = profile
            else:
                number = len(labels) + 1
                label = f"Speaker {number}"
                while label in profile_labels or label in labels.values():
                    number += 1
                    label = f"Speaker {number}"
                labels[speaker] = label
            profile_ids[speaker] = profile
        text = (
            "".join(token.text for token in tokens).strip()
            if tokens
            else sentence.text.strip()
        )
        if not text:
            continue
        related = [t for t in turns if t.speaker == speaker]
        confidence_values = [t.confidence for t in related if t.confidence is not None]
        confidence = (
            sum(confidence_values) / len(confidence_values)
            if confidence_values
            else None
        )
        start = tokens[0].start if tokens else sentence.start
        end = tokens[-1].end if tokens else sentence.end
        overlap = any(
            t.overlap and t.start < end and t.end > start
            for t in related
        )
        if (
            segments
            and segments[-1].speaker == labels[speaker]
            and segments[-1].overlap == overlap
        ):
            segments[-1].text = (segments[-1].text + " " + text).strip()
            segments[-1].end = end
        else:
            segments.append(
                MeetingSegment(
                    speaker=labels[speaker],
                    start=start,
                    end=end,
                    text=text,
                    confidence=confidence,
                    overlap=overlap,
                    profile_id=profile_ids[speaker],
                    cluster_id=speaker,
                )
            )
    return segments


def known_speaker_segments(sentences, speaker: str = "You") -> list[MeetingSegment]:
    """Convert one known-source ASR track without running diarization."""
    segments = []
    for sentence in sentences or []:
        text = sentence.text.strip()
        if not text:
            continue
        if segments and segments[-1].speaker == speaker:
            segments[-1].text = (segments[-1].text + " " + text).strip()
            segments[-1].end = float(sentence.end)
        else:
            segments.append(
                MeetingSegment(
                    speaker=speaker,
                    start=float(sentence.start),
                    end=float(sentence.end),
                    text=text,
                )
            )
    return segments


def shift_segments(
    segments: list[MeetingSegment], offset_seconds: float
) -> list[MeetingSegment]:
    for segment in segments:
        segment.start = max(0.0, segment.start + offset_seconds)
        segment.end = max(segment.start, segment.end + offset_seconds)
    return segments


def merge_tracks(*tracks: list[MeetingSegment]) -> list[MeetingSegment]:
    """Chronologically merge independent tracks without transcript cleanup.

    Deliberately do not remove similar text across tracks: repeated phrases and
    real overlap are valid meeting content, while speaker-mode echo cannot be
    distinguished reliably from text alone.
    """
    indexed = [
        (segment.start, segment.end, track_index, segment_index, segment)
        for track_index, track in enumerate(tracks)
        for segment_index, segment in enumerate(track)
    ]
    indexed.sort(key=lambda item: item[:4])
    return [item[-1] for item in indexed]
