"""Meeting transcripts: speaker-attributed dialogue, stored as plain JSON.

Only the transcript is ever persisted — meeting audio spools to a temp WAV
during recording and is deleted the moment processing finishes (or fails, or
is cancelled). Each meeting is one hand-editable JSON file in
settings.meetings_dir(), keyed by an immutable id so renaming never moves a
file:

    {
      "id": "20260708-143212-a3f9",
      "title": "Meeting — Jul 8, 2:32 PM",
      "created": "2026-07-08T14:32:12",
      "duration_seconds": 1832.5,
      "segments": [
        {"speaker": "Speaker 1", "start": 0.4, "end": 12.9, "text": "..."}
      ]
    }

This module is pure logic (stdlib only) so the alignment algorithm and the
store are testable without the model, sherpa-onnx, or AppKit. The alignment
inputs are duck-typed: `sentences` only needs .start/.end/.tokens (tokens
need .start/.end/.duration/.text), matching parakeet_mlx's AlignedSentence
without importing it.
"""

import json
import os
import re
import secrets
from dataclasses import dataclass
from datetime import datetime

from . import settings

# Ids double as filenames; generated by Meeting.new, validated on load.
_ID_RE = re.compile(r"[0-9]{8}-[0-9]{6}-[0-9a-f]{4}")

# A diarization turn further than this from a token is considered unrelated;
# the token then inherits its predecessor's speaker instead (mid-sentence
# continuity beats a distant turn).
_MAX_TURN_DISTANCE_SECONDS = 2.0


@dataclass
class MeetingSegment:
    speaker: str
    start: float
    end: float
    text: str


class Meeting:
    def __init__(
        self,
        meeting_id: str,
        title: str,
        created: str,
        duration_seconds: float,
        segments: list[MeetingSegment],
    ) -> None:
        self.meeting_id = meeting_id
        self.title = title
        self.created = created
        self.duration_seconds = duration_seconds
        self.segments = segments

    # -- storage --------------------------------------------------------

    @property
    def path(self):
        return settings.meetings_dir() / f"{self.meeting_id}.json"

    @classmethod
    def new(cls, segments: list[MeetingSegment], duration_seconds: float) -> "Meeting":
        now = datetime.now()
        meeting_id = f"{now.strftime('%Y%m%d-%H%M%S')}-{secrets.token_hex(2)}"
        # e.g. "Meeting — Jul 8, 2:32 PM" (%-I is glibc/BSD strftime; fine on macOS)
        title = f"Meeting — {now.strftime('%b %-d, %-I:%M %p')}"
        return cls(
            meeting_id=meeting_id,
            title=title,
            created=now.isoformat(timespec="seconds"),
            duration_seconds=duration_seconds,
            segments=segments,
        )

    @classmethod
    def load(cls, meeting_id: str) -> "Meeting":
        # Same defense as Profile.load: the id becomes a filesystem path and
        # must not be trusted blindly.
        if not _ID_RE.fullmatch(meeting_id):
            raise ValueError(f"Invalid meeting id: {meeting_id!r}")
        path = settings.meetings_dir() / f"{meeting_id}.json"
        data = json.loads(path.read_text(encoding="utf-8"))
        segments = [
            MeetingSegment(
                speaker=str(s["speaker"]),
                start=float(s["start"]),
                end=float(s["end"]),
                text=str(s["text"]),
            )
            for s in data.get("segments", [])
        ]
        return cls(
            meeting_id=meeting_id,
            title=data.get("title") or meeting_id,
            created=data.get("created") or "",
            duration_seconds=float(data.get("duration_seconds", 0.0)),
            segments=segments,
        )

    def save(self) -> None:
        """Write the meeting as JSON, atomically (same rationale as
        Profile.save: never leave a half-written file for the list to skip)."""
        self.path.parent.mkdir(parents=True, exist_ok=True)
        data = (
            json.dumps(
                {
                    "id": self.meeting_id,
                    "title": self.title,
                    "created": self.created,
                    "duration_seconds": self.duration_seconds,
                    "segments": [
                        {
                            "speaker": s.speaker,
                            "start": round(s.start, 2),
                            "end": round(s.end, 2),
                            "text": s.text,
                        }
                        for s in self.segments
                    ],
                },
                indent=2,
                ensure_ascii=False,
            )
            + "\n"
        )
        tmp_path = self.path.with_suffix(".json.tmp")
        tmp_path.write_text(data, encoding="utf-8")
        os.replace(tmp_path, self.path)

    def rename(self, title: str) -> None:
        title = title.strip()
        if not title:
            raise ValueError("Meeting title can't be empty.")
        self.title = title
        self.save()

    def delete(self) -> None:
        self.path.unlink(missing_ok=True)


def list_meetings() -> list[Meeting]:
    """Every stored meeting, newest first, skipping any that won't parse
    (hand-editable JSON — one bad file must not take the list down)."""
    meetings_dir = settings.meetings_dir()
    meetings = []
    for path in meetings_dir.glob("*.json"):
        if not _ID_RE.fullmatch(path.stem):
            continue
        try:
            meetings.append(Meeting.load(path.stem))
        except (OSError, ValueError, KeyError) as err:
            print(f"  Skipping meeting '{path.stem}' (couldn't read it): {err}")
    meetings.sort(key=lambda m: m.meeting_id, reverse=True)
    return meetings


# -- rendering ------------------------------------------------------------


def _timestamp(seconds: float) -> str:
    seconds = max(0, int(seconds))
    h, rem = divmod(seconds, 3600)
    m, s = divmod(rem, 60)
    return f"{h:02d}:{m:02d}:{s:02d}"


def _duration_text(seconds: float) -> str:
    m = int(seconds) // 60
    if m >= 60:
        return f"{m // 60} h {m % 60} min"
    return f"{m} min" if m else f"{int(seconds)} s"


def render_txt(meeting: Meeting) -> str:
    lines = [
        meeting.title,
        f"{meeting.created}  ·  {_duration_text(meeting.duration_seconds)}",
        "",
    ]
    for seg in meeting.segments:
        lines.append(f"[{_timestamp(seg.start)}] {seg.speaker}: {seg.text}")
    return "\n".join(lines) + "\n"


def render_md(meeting: Meeting) -> str:
    lines = [
        f"# {meeting.title}",
        "",
        f"*{meeting.created}  ·  {_duration_text(meeting.duration_seconds)}*",
        "",
    ]
    for seg in meeting.segments:
        lines.append(f"**{seg.speaker}** [{_timestamp(seg.start)}]: {seg.text}")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


# -- speaker/text alignment -------------------------------------------------


def align_speakers(sentences, turns) -> list[MeetingSegment]:
    """Attribute transcribed sentences to diarization speakers.

    `sentences`: time-ordered objects with .start/.end/.tokens (tokens carry
    .start/.end/.duration/.text) — parakeet_mlx AlignedSentence-shaped.
    `turns`: [(start, end, speaker_int)] from the diarizer, any order.

    Tokens vote for the turn containing their midpoint; a token in no turn
    falls to the nearest turn unless it is further than
    _MAX_TURN_DISTANCE_SECONDS away, in which case it inherits its
    predecessor's speaker (the diarizer missed a beat mid-utterance more
    often than the room actually changed speakers). Each sentence goes to
    its duration-majority speaker — sentence-level voting absorbs the jitter
    tokens pick up at turn boundaries. Consecutive same-speaker sentences
    merge into one segment, and speakers are numbered by first appearance.
    """
    if not sentences:
        return []
    turns = sorted(turns, key=lambda t: t[0])

    def token_speaker(token, previous: int | None) -> int | None:
        mid = (token.start + token.end) / 2
        nearest, nearest_distance = None, None
        for start, end, speaker in turns:
            if start <= mid <= end:
                return speaker
            distance = start - mid if mid < start else mid - end
            if nearest_distance is None or distance < nearest_distance:
                nearest, nearest_distance = speaker, distance
        if nearest is None:
            return previous
        if nearest_distance > _MAX_TURN_DISTANCE_SECONDS and previous is not None:
            return previous
        return nearest

    # Sentence → speaker by duration-weighted majority of its tokens.
    sentence_speakers: list[int] = []
    previous: int | None = None
    for sentence in sentences:
        weights: dict[int, float] = {}
        for token in sentence.tokens:
            speaker = token_speaker(token, previous)
            if speaker is None:
                continue
            previous = speaker
            weights[speaker] = weights.get(speaker, 0.0) + max(token.duration, 1e-3)
        if weights:
            winner = max(weights.items(), key=lambda kv: kv[1])[0]
        else:
            # No turns at all (diarization found nothing): single speaker.
            winner = sentence_speakers[-1] if sentence_speakers else 0
        sentence_speakers.append(winner)

    # Merge consecutive same-speaker sentences; label by first appearance.
    labels: dict[int, str] = {}
    segments: list[MeetingSegment] = []
    for sentence, speaker in zip(sentences, sentence_speakers):
        if speaker not in labels:
            labels[speaker] = f"Speaker {len(labels) + 1}"
        text = sentence.text.strip()
        if not text:
            continue
        if segments and segments[-1].speaker == labels[speaker]:
            segments[-1].text += " " + text
            segments[-1].end = sentence.end
        else:
            segments.append(
                MeetingSegment(
                    speaker=labels[speaker],
                    start=sentence.start,
                    end=sentence.end,
                    text=text,
                )
            )
    return segments
